version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build-and-test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: |
            sudo rm /usr/local/bin/bundle
            sudo gem update --system
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run specs
          command: bundle exec rake spec

workflows:
  build-and-test:
    jobs:
      - build-and-test
